export default {
  INIT_AGE_LIST: 'initAgeList',
  TOGGLE_DONE: 'toggleDone',
  GET_START: 'getStart',
  NEXT: 'next',
  SET_INDEX: 'setIndex',
  CHOOSE_SEX: 'chooseSex',
  SELECT_MEMBERS: 'selectMembers',
  STOP_SWIPER: 'stopSwiper',
  USE_SWIPER: 'useSwiper',
  ADD_AGE: 'addAge',
  ADD_RESIDENCE: 'addResidence',
  ADD_SOCIAL: 'addSocial',
  ADD_INCOME: 'addIncome',
  ADD_SMOKE: 'addSmoke',
  TOGGLE_AGE_PICKER: 'toggleAgePicker',
  TOGGLE_CITY_PICKER: 'toggleCityPicker',
  TOGGLE_KEYBOARD: 'toggleKeyboard',
  SET_CHOOSE_LIST: 'setChooseList',
  SET_DEFAULT_AGE: 'setDefaultAge',
  SET_AGE: 'setAge',
  SET_INPUT_NUMBER: 'setInputNumber',
  TOGGLE_MODIFY: 'toggleModify',
  CLEAR: 'clear'
}
